### ISSUE TITLE
Rate limit for writes exceeded when patching using GAAudiencesUpdater

### ISSUE THREAD

**Issue by tyroneschiff** [google/crmint#202]
I am using the GAAudiencesUpdater to update audiences. The GAAudiencesUpdater seems to handle the creation of the audiences the first time fine, however, when the pipeline runs on subsequent days and uses the patch method the job fails every time.

The error I'm getting is: Unexpected error: HttpError: <HttpError 403 when requesting https://www.googleapis.com/analytics/v3/management/accounts/xxx/webproperties/UA-xxx-17/remarketingAudiences/xxx?alt=json returned "Quota Error: Rate limit for writes exceeded.">

Screenshot from the CRMint attached.
![W9G9LU4v55TrWga](https://user-images.githubusercontent.com/452271/98555484-fdd15200-226f-11eb-91be-76ce07a02f65.png)

Would appreciate any guidance on why this may be the case with the patch method specifically? Thanks!

**Comment by tyroneschiff** [comment]
Also submitted to Stack Overflow: [https://stackoverflow.com/questions/64753902/crmint-rate-limit-for-writes-exceeded-when-patching-using-gaaudiencesupdater](url)

**Comment by PA-Mousset** [comment]
Honestly, I would avoid using CRMint, there is a lot of bugs and seems no one is maintaining this repo now.

**Comment by Slony** [comment]
Hi @PA-Mousset, thank you for your honest — though somewhat discouraging — feedback.

At the moment, CRMint core team is busy with migrating CRMint to Google App Engine Standard environment for Python 3.

CRMint is an open-source project, and anyone can contribute to it by submitting:

- feature requests,
- detailed bug reports,
- pull requests aimed at:
  - fixing the bugs,
  - implementing new features, and
  - improving the documentation.

Please, get familiar with [CRMint Contributor's Guide](https://github.com/google/crmint/wiki/Contributor's-Guide) to learn more and start contributing to the project.

**Comment by Slony** [comment]
Fixed by #204.

Thank you @tyroneschiff and @PA-Mousset for reporting this issue: it helped to find and fix a logic error in one of CRMint's retry mechanisms.

Please [re-deploy CRMint from dev branch](https://github.com/google/crmint/wiki/Deploy-CRMint-on-Google-Cloud-Platform-from-the-dev-branch).

⚠️  **Please note** that the internal bug that prevents the Google Analytics Management API from updating Remarketing Audiences in some Google Analytics accounts is **not fixed** yet. It mean that CRMint **won't be able** to update the audiences in the accounts affected until the bug is fixed.

**Comment by tyroneschiff** [comment]
Just a follow up on this issue. The client redeployed the CRMint instance with this code change enabled. However, now when they are updating audiences they are getting a 500 error. 

I know you mentioned in your last comment that there is a Google Analytics bug that is not fixed for updating certain Google Analytics accounts. Can you share that bug please and is there any way to know whether or not this client is being impacted by that?

I've attached a screenshot. Would you prefer I open up a new issue for this? Thank you!

<img width="902" alt="Propensity Pipeline Error" src="https://user-images.githubusercontent.com/452271/99699631-291e2300-2a60-11eb-9c96-4ece43ac9fbe.PNG">
